chore: configure project
kristinavlasovets/client-blog pull request #1
Opened 2023-06-28 14:07 UTC by kristinavlasovets

clickUp task: https://app.clickup.com/t/861n000v0

2023-06-30 14:54 UTC, anyaprystavka requested changes

2023-06-30 14:54 UTC, anyaprystavka commented on .github/workflows/github-actions-demo.yml
> +      - name: actions-checkout
еще нужно подключить eslint и тесты

2023-06-30 14:54 UTC, anyaprystavka commented on package.json
> +    "build-storybook": "storybook build"
еще Prettier нужен

2023-06-30 14:54 UTC, anyaprystavka commented on package.json
> +    "eslint-config-next": "13.4.7",
нужно пересмотреть dependencies

2023-06-30 14:54 UTC, anyaprystavka commented on src/components/Block/styles.module.scss
> +  padding: 0 3%;
проценты убираем

2023-06-30 14:54 UTC, anyaprystavka commented on src/components/Header/styles.module.scss
> +  padding: 0 3%;
проценты

2023-06-30 14:54 UTC, anyaprystavka commented on src/components/Header/styles.module.scss
> +  display: flex;
часто могут повторять стили
например с flex'ами
можно в глобал styles вынести и подключать в нужно месте(для переиспользования)

2023-06-30 14:54 UTC, anyaprystavka commented on src/components/Header/styles.module.scss
> +  padding-left: 20%;
проценты

2023-06-30 14:54 UTC, anyaprystavka commented on src/components/HeaderBase/HeaderBase.tsx
> +          .filter((l) => lng !== l)
названия всем переменных даем понятные

2023-06-30 18:28 UTC, kristinavlasovets commented on package.json
> +    "build-storybook": "storybook build"
Выполнено: 
"format": "prettier --write \"./src/**/*.{js,jsx,ts,tsx,json,css,scss,md}\"",

2023-07-01 18:18 UTC, anyaprystavka requested changes

2023-07-01 18:18 UTC, anyaprystavka commented on src/types/index.ts
> +export interface ErrorBoundaryState {
можно объявить в ErrorBoundary -т.к. используется 1 раз

2023-07-01 18:18 UTC, anyaprystavka commented on package.json
> +    "@types/node": "20.3.2",
все types это devDependencies

2023-07-01 18:18 UTC, anyaprystavka commented on src/components/HeaderBase/HeaderBase.tsx
> +          .filter((l) => lng !== l)
не исправлено(23 строка)

2023-07-01 18:56 UTC, anyaprystavka approved these changes

2023-07-01 19:35 UTC, merged